[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PRIVATE_TARGET = "server"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  targetPort = 3002

[functions]
  included_files = ["lib/**", "hooks/**", "stores/**", "types/**", "database/migrations/**"]
